### ISSUE TITLE
Settings allow you to to disable error/warning/info messages entirely

### ISSUE THREAD

**Issue by vadi2** [health-validator/Hammer#113]
**Describe the bug**
Settings allow you to to disable error/warning/info messages entirely which means that you'll then simply get a blank status box and no messages. Doesn't look very good.

**To Reproduce**
Turn off error, warning, informational messages and hit `Validate`.

**Expected behavior**
Settings should not allow you to disable _all_ types - at least one should be on.

**Comment by pieter-edelman-nictiz** [comment]
Maybe it would be an option to *always* display errors? This is what determines the pass or fail result after all. And I wonder if it makes much sense to display warnings and/or info messages but not errors.

**Comment by vadi2** [comment]
Perfect. How about this:

# Always show errors and...

[ ] Warnings [ ] Info

**Comment by pieter-edelman-nictiz** [comment]
Great! Or just 'Show errors and...'

**Comment by vadi2** [comment]
Yep.

**Comment by vadi2** [comment]
I'm not sure what did I do that it auto-assigns issues to me :thinking:
