### ISSUE TITLE
Validation Against Profiles

### ISSUE THREAD

**Issue by jawalonoski** [health-validator/Hammer#123]
How do you configure Hammer to find, use, or ignore profiles and extensions?

Tested it with an R4 Patient Bundle from Synthea using the latest Mac OS X download.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/1054765/60829672-693e7780-a183-11e9-924c-10acac2904b2.png">

I expected it to issue warnings or something about extensions it didn't recognize, rather than erroring, or to recognize US-Core by default (yes, I know, how very US-centric of me).

**Comment by vadi2** [comment]
Right now the instance is validated against the profiles it claims conformance to in `meta.profile` - no explicit setting for it. 

(and ooh, it looks amazing on a Retina...)

**Comment by vadi2** [comment]
And to set the scope of validation - where to find the profiles, go to the hamburger bottom-right. If you hover over the `Validate` button, it'll also tell you the scope.

By default it's auto-set to the same folder (and and sub-folders) of the instance you used.
