### ISSUE TITLE
Fresh Download of Hammer for Mac OS X does not include Java Validator

### ISSUE THREAD

**Issue by jawalonoski** [health-validator/Hammer#124]
I downloaded a fresh copy of Hammer using the download link from the README, and validated a FHIR Bundle... the distribution does not seem to contain the Java validator:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/1054765/60829911-0ef1e680-a184-11e9-838f-1f402ea9f55d.png">

**Comment by vadi2** [comment]
Sorry about - fixed, try again.

**Comment by jawalonoski** [comment]
Fixed.
