### ISSUE TITLE
Cancel current Java validation when starting another one

### ISSUE THREAD

**Issue by vadi2** [health-validator/Hammer#35]
**Describe the bug**
When you restart validation before the existing Java validation is finished, a new Java process is spawned without stopping the existing one. If you hit Validate shortcut `Ctrl+D` very many times in a row, you can spawn enough Java validators to use up all of the computers memory and thus lock it up.

**To Reproduce**
1. Load an instance
1. Press `Ctrl+D` ten times quickly

**Expected behavior**
Previous Java validation should be cancelled right away before a new one is started.

**Comment by pieter-edelman-nictiz** [comment]
This issue can be closed now, right?
