### ISSUE TITLE
QML signal for ValidationReport.WarningCount is never raised

### ISSUE THREAD

**Issue by vadi2** [health-validator/Hammer#39]
**Describe the bug**
QML signal for ValidationReport.WarningCount is never raised - only QML signal for ValidationReport.ErrorsCount. This makes any bindings that depend on WarningCount not work. Read-access seems to be fine, though. 

**To Reproduce**
1. Validate a resource which has 0 errors and some warnings - you'll see that the warning count is never updated.
1. or, change WarningCount to be updated after ErrorCount

**Expected behavior**
WarningCount should be updated correctly.

**Additional context**
Maybe the issue lies in it being a nested property?

**Comment by pieter-edelman-nictiz** [comment]
This issue can be closed now, right?

**Comment by vadi2** [comment]
I think so. Though it is strange that .NET error count doesn't show until the Java one is finished, haven't looked into that yet.

**Comment by pieter-edelman-nictiz** [comment]
Good point. I'll open a bug report
