### ISSUE TITLE
Validation isn't stopped when pressing the 'back' button

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [health-validator/Hammer#62]
When pressing the 'Validate' button, the app kicks off both validators and switches to the results page, where you can press the 'back' button. However, the validators keep on running, and when you press 'Validate' again, they might interfere with the newly created instances.

So the validators should probably be killed when pressing the 'back' button, or alternatively a check should be done if there are still old validators running when pressing the 'Validate' button.

**Comment by vadi2** [comment]
Agreed. This is similar to https://github.com/health-validator/Hammer/issues/35. I think we could cancel it both on the 'back' button and also at the start of validation, in case you re-validate without hitting back.

**Comment by pieter-edelman-nictiz** [comment]
Ah yes, missed that one. I do think the .Net validator should be included as well though - it's much faster, but it's a long-running process as well.
