### ISSUE TITLE
Java validator errors when pasting content

### ISSUE THREAD

**Issue by mbaltus** [health-validator/Hammer#78]
**Describe the bug**
When you use the "Load it here" field instead of opening a file, and paste content in it, the Java validator errors with an exception:
"Exception in thread ""main"" java.lang.Exception: Unable to find/resolve/read -ig "

**To Reproduce**
1. Copy a json resource text so it's on your clipboard
2. Start Hammer and paste into the "Load it here" field
3. Click "validate"
4. See Java error

**Desktop (please complete the following information):**
 - macOS

**Additional context**
Since I pasted the content, there is no scope, and that might be the problem for the validator.

**Comment by vadi2** [comment]
That makes sense - will fix!

**Comment by vadi2** [comment]
Fixed
