### ISSUE TITLE
Add option to load another resource after opening editor

### ISSUE THREAD

**Issue by mbaltus** [health-validator/Hammer#82]
**Is your feature request related to a problem? Please describe.**
When you validate a resource, and click on an error, the editor window opens. This is a nice feature. However, you cannot go back anymore - only re-validate - and therefore the option to open another resource is gone, because that is Back --> Open.

**Describe the solution you'd like**
I would like to have a button that makes it possible to open another resource. This could be a button to go back so you have the Open button again, or an Open button on the validation page.

**Describe alternatives you've considered**
The Ctrl-O shortcut does work, of course, but is not obvious to all.

**Additional context**
In order to limit the number of buttons on the validation page, I would also find it acceptable to go to the Settings, and being able to view the "Open file/Load it here" dialog on that page again, even though it is not really a setting. Or, alternatively, replacing the Settings button with the option to go back, although less desirable, since you might want to change the scope during validation.

**Comment by vadi2** [comment]
What about moving the button to copy the report into a right-click option on any error? That seems more or less intuitive way to find that functionality and then we'd have space for opening another instance again.

(also, dragging and dropping a resource onto Hammer would work to open it - but not on Windows https://github.com/health-validator/Hammer/issues/69)

**Comment by mbaltus** [comment]
Yes, that sounds like a good idea. At the moment I click on the copy button all the time, mistaking it for the open button. :)

**Comment by vadi2** [comment]
Ha, okay, so changing the functionality of a button on you is not a good idea. Noted.
