### ISSUE TITLE
Editor does not close anymore, Back button does not work

### ISSUE THREAD

**Issue by mbaltus** [health-validator/Hammer#83]
**Describe the bug**
When you have clicked on a validation error, and the editor opens, it reappears when you've gone back to the resource text, or have opened another resource and validate that.
The button at the bottom shows "Back", but it does not work to go back, instead doing a re-validate.

**To Reproduce**
1. Open a resource that has an error, and click on 'validate'
2. Click on the error to open the editor
3. Use Ctrl-O to open another resource
4. Click 'validate' to see that the editor is still open
5. Click on 'Back' to see that this performs a 're-validate' instead of going back

**Expected behavior**
I expected a 'clean' validation screen in step 4, and the 'Back' button to go back to the resource instead of performing the 're-validate'.

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by vadi2** [comment]
Fixed now.
