### ISSUE TITLE
Mirror error/warning/info settings in result count

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [health-validator/Hammer#94]
**Is your feature request related to a problem? Please describe.**
You can tell Hammer if you want to show errors, warnings and/or info messages. However, the result boxes always tell you the number of warnings and errors regardless of these settings.

**Describe the solution you'd like**
The result boxes should show the number of errors, warnings and messages if they are requested, or hide each of these components if they are not requested.

**Comment by vadi2** [comment]
@pieter-edelman-nictiz btw: if you do something like 'fix <issue link>' or 'resolve <issue link>', Github will pick that up and auto-close the original issue when the PR is merged.

**Comment by pieter-edelman-nictiz** [comment]
You mean in the description?

**Comment by vadi2** [comment]
Yeah.

**Comment by pieter-edelman-nictiz** [comment]
Ah, good to know. Thanks!
