### ISSUE TITLE
Persist settings

### ISSUE THREAD

**Issue by pieter-edelman-nictiz** [health-validator/Hammer#95]
**Is your feature request related to a problem? Please describe.**
You can configure Hammer in several ways, but these settings are not re-used when you open the app again.

**Describe the solution you'd like**
Save the settings and load them when you open the app again.

**Comment by vadi2** [comment]
Definitely need this. It seems that saving settings with .NET Core is an absolute mess if you google around - I'd rather use QSettings for this, but unless we do it from the QML side (which doesn't seem so declarative anymore?), we'd have to add bindings to Qml.Net. (or switch to unmanaged hosting where we launch a C++ application that bootstraps C# and Qml.Net)

**Comment by pieter-edelman-nictiz** [comment]
QSettings is really nice. QML also has Settings which seems to provide similar functionality (somewhat experimental) : https://doc.qt.io/qt-5/qml-qt-labs-settings-settings.html. I think it's an elegant solution.

**Comment by vadi2** [comment]
The other option is just a home-made JSON file which is what Torinox uses.

My only issue with QSettings via QML is that is takes away from the nice, clean setup we have were QML only worries about display and the C# backend takes care of the rest. Ideally it'd be C# that is doing the saving. But I won't be a purist for the sake of it, practical functionality is more important.
